Modifico el Makefile de root agregando a la regla all que haga install, modifico el readme
sisoputnfrba/parsi pull request #2
Opened 2018-04-24 14:00 UTC by ltrinidad

2018-04-25 22:58 UTC, jazcarate requested changes

2018-04-25 22:58 UTC, jazcarate commented on Makefile
> +	-cd src && sudo $(MAKE) install
Estaría buenisimo que el `all` no instalase. Instalar te fuerza a usar `su`, y tal vez podes vivir solo compilando la biblioteca.
Lo moverías otro target especifico de `install`, así te quedaría:


```
all: 
	-cd src && $(MAKE) all
	-cd tests && $(MAKE) all
install:
	-cd src && sudo $(MAKE) install
```

2018-04-25 22:58 UTC, jazcarate commented on README.md
> +Desde la consola clonar el repo, luego meterse dentro de la carpeta parsi y ahi ejecutar el comando make o make all (en un momento se frena la instalacion porque espera el pasword del super-usuario,
el comando debería ser ahora `sudo make install`; así es más _intention revealing_ y no necesitamos la aclaración de pedir contraseña de super-usuario.

2018-04-26 21:19 UTC, ltrinidad reviewed
Listo ! Pero antes de commitear los cambios la duda que me queda es que, si vos queres que el único comando de instalación sea sudo make install por que no hay que hacer que install dependa de all ? (quiero decir : 
install : all 
      - cd src && sudo $(MAKE) install
)
O entendi mal y hay que hacer make all y despues make install ?

2018-04-26 21:22 UTC, jazcarate commented
Creería que el `install` dentro de `src` depende de su `all`.

2018-04-26 21:30 UTC, ltrinidad commented
AAAAAAAH claro!!

2018-04-26 21:37 UTC, jazcarate approved these changes

2018-04-26 21:38 UTC, ltrinidad commented
Listo Joaco!!! Ahí pushee los cambios a este fork. Muchas gracias por dejarme participar 😄

2018-04-26 21:38 UTC, merged